### ISSUE TITLE
Usage question about plugin.cfg

### ISSUE THREAD

**Issue by sh-cho** [dugramen/godot-globalize-plugins#2]
I'm new to this plugin and godot so I have some question about usage.

Assume I installed plugin A on project A, plugin B on project B, ...
And now I want to enable all plugins among all projects.

Then, I should add paths like `/..../projectA/addons/pluginA/plugin.cfg`, `/..../projectB/addons/pluginB/plugin.cfg`, ...

I wonder In this case, what should I do if I want to remove project B in my disk. Should I move plugin B to other project?

**Comment by dugramen** [comment]
If you want to keep plugin b then yeah. And also update the path in EditorSettings

Though I think I see the issue you're bringing up. I'm assuming you're downloading a plugin from the asset store, and you don't want the "globalization" to be tied to a specific project

For now, it might be a good idea to have a single project specifically for containing plugins that should be global

**Comment by dugramen** [comment]
But I might be able to add another editor property, where instead of file paths, you have a list of URLs. The URLs could point to plugins in the asset store, and synced into the project from there. I'll have to experiment a bit

Edit: nvm, the asset library doesn't have a public api

**Comment by sh-cho** [comment]
> If you want to keep plugin b then yeah. And also update the path in EditorSettings
> 
> Though I think I see the issue you're bringing up. I'm assuming you're downloading a plugin from the asset store, and you don't want the "globalization" to be tied to a specific project
> 
> For now, it might be a good idea to have a single project specifically for containing plugins that should be global

Well understood.

> But I might be able to add another editor property, where instead of file paths, you have a list of URLs. The URLs could point to plugins in the asset store, and synced into the project from there. I'll have to experiment a bit
> 
> Edit: nvm, the asset library doesn't have a public api

Have you check [this api document](https://github.com/godotengine/godot-asset-library/blob/master/API.md)? 

Looks like this can be used.

```sh
$ curl --request GET \
       --url https://godotengine.org/asset-library/api/asset/2681

{
	"asset_id": "2681",
	"type": "addon",
	"title": "Globalize Plugins",
	"author": "dugramen",
	"author_id": "13830",
	"version": "1",
	"version_string": "1.0",
	"category": "Tools",
	"category_id": "5",
	"godot_version": "4.2",
	"rating": "0",
	"cost": "MIT",
	"description": "This plugin lets you globalize other plugins. Globalized plugins get copied into the current project when loaded, keeping them up to date and adding any new plugins you've globalized since.\r\n\r\nTo globalize plugins, go to Editor > EditorSettings > Global Plugins > Paths, and add the plugin.cfg of your plugin.\r\n\r\nTo enable global plugins in a project, just download and enable this plugin, and all your globalized plugins will be added automatically (You only have to do this once per project).",
	"support_level": "community",
	"download_provider": "GitHub",
	"download_commit": "6da8eb783547c4fd6b2c02edc3b8e2d5a4f61af3",
	"browse_url": "https:\/\/github.com\/dugramen\/godot-globalize-plugins",
	"issues_url": "https:\/\/github.com\/dugramen\/godot-globalize-plugins\/issues",
	"icon_url": "https:\/\/raw.githubusercontent.com\/dugramen\/godot-globalize-plugins\/master\/globalize-plugin.png",
	"searchable": "1",
	"modify_date": "2024-03-14 19:39:19",
	"download_url": "https:\/\/github.com\/dugramen\/godot-globalize-plugins\/archive\/6da8eb783547c4fd6b2c02edc3b8e2d5a4f61af3.zip",
	"previews": [],
	"download_hash": ""
}
```

**Comment by dugramen** [comment]
Thanks! Don't know how I missed that

I was experimenting with parsing the Asset Library's node tree and grabbing the repository link from there. I might be able to inject a "Globalize" button directly into the download prompt that way. But if that gets too complicated I'll just settle for a simple search UI with their api

**Comment by dugramen** [comment]
You can now globalize AssetLib plugins in #3
