### ISSUE TITLE
its giving this errors for me

### ISSUE THREAD

**Issue by csocraman** [dugramen/godot-globalize-plugins#4]
its giving this errors for me:
res://addons/globalize-plugins/asset_panel.gd
  Line 6:Preload file "res://addons/globalize-plugins/saved_versions.tres" does not exist.
  Line 6:Cannot infer the type of "versions" variable because the value doesn't have a set type.

res://addons/globalize-plugins/plugin.gd
  Line 6:Preload file "res://addons/globalize-plugins/saved_versions.tres" does not exist.
  Line 6:Cannot infer the type of "versions" variable because the value doesn't have a set type.

**Comment by dugramen** [comment]
Thanks! Fixed by 228b3ce

It'll take a few days to go live in the asset library
