### ISSUE TITLE
Too many errors

### ISSUE THREAD

**Issue by RiOnE03** [dugramen/godot-globalize-plugins#6]
I am on godot 4.3. It seems the build is for 4.2. But I tried using it anyway. It works for the editor settings parts but after using it the output log is filled with errors. I haven't tested the asset library yet but after adding through editor settings. The added plugin don't show in the Globalized tab. I don't know if it was not supposed to do that or what. I think this addon is useful so I'll try to figure out what is going wrong.

**Comment by dugramen** [comment]
Sorry didn't see this until now. The globalized tab, and that whole window in general, is just for asset library plugins.

To clarify, you still enable and disable plugins how you usually would, in `ProjectSettings > Plugins`. All globalize-plugins does is copy them into your project, and tries to enable them for the first time automatically (which can cause some plugins to spit out errors).

But there is a bug, where the list of plugins doesn't update immediately. What should happen is you go to your plugins list, enable globalize-plugins, and all your globalized plugins appear in that list and are automatically enabled. But I think currently, if you don't have any asset library plugins, then the list won't update until you close & reopen the list (but they'll still be enabled silently)
